- name: Variables from files
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print cource information
    ansible.builtin.debug:
      msg: "Hello Iam learning {{ COURCE }}, Duration: {{ DURATION }}, Trainer is: {{ TRAINER }} "
