- name: variables from inventory
  hosts: frontend
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello I am learning {{ COURCE }}, Duration is: {{ DURATION }}, Trainer is: {{ TRAINER }}"
