- name: ansible datatypes
  hosts: local
  connection: local
  vars:
    DURATION: 120  # This is number
    COURCE: "DevSecOps with AWS"  # This is string
    IS_LIVE: true  # boolean
    TOOLS:   # start with hyphen is list, reffered by []
    - Linux
    - shell
    - Ansible
    CONCEPTS:  # map or dictornary in python or object, reffered like {}
      CI: Jenkins
      SCRIPTING: "Shell, Ansible, Terraform, python"
  tasks:
  - name: print cource information
    ansible.builtin.debug:
      msg: "Cource is: {{ COURCE }}, Duration is : {{ DURATION }}, is live?: {{ IS_LIVE }}, Tools are: {{ TOOLS }}, Concepts are: {{ CONCEPTS }}"
