- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh,Suresh,Raheem,Joseph"
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ PERSON | default('suresh')}}"

  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ persons | split(',') }}"

  - name: convert map into list
    vars:
      cource:
        name: ansible
        duration: 10HRS
        trainer: siva
    ansible.builtin.debug:
      msg: "Cource Info: {{ cource | dict2items }}"

  - name: convert list into map
    vars:
      cource:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10HRS'}
      - {'key': 'trainer', 'value': 'siva'}
    ansible.builtin.debug:
      msg: "Cource Info: {{ cource | items2dict }}"

  - name: convert to uppercase
    vars:
      name: "Mohan Prasad"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"

  - name: convert to lower case
    vars:
      name: "MOHAN PRasad"
    ansible.builtin.debug:
      msg: "Hello {{ name | lower}}"

  - name: check IP address is valid or not  # max IP address range is 255.255.255.255
    vars:
      ip: "555.333.222.11"
    ansible.builtin.debug:
     msg: "{{ ip | ansible.utils.ipaddr }}"