- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh,Suresh,Raheem,Joseph"
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ PERSON | default('suresh')}}"

  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ persons | split(',') }}"

  - name: convert map into list
    vars:
      cource:
        name: ansible
        duration: 10HRS
        trainer: siva
    ansible.builtin.debug:
      msg: "Cource Info: {{ cource | dict2items }}"